export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";

// Employee Types
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const ONBOARDING_SUBMIT_REQUEST = "ONBOARDING_SUBMIT_REQUEST";
export const ONBOARDING_SUBMIT_SUCCESS = "ONBOARDING_SUBMIT_SUCCESS";
export const ONBOARDING_SUBMIT_FAIL = "ONBOARDING_SUBMIT_FAIL";

export const FETCH_DOCUMENTS_REQUEST = "FETCH_DOCUMENTS_REQUEST";
export const FETCH_DOCUMENTS_SUCCESS = "FETCH_DOCUMENTS_SUCCESS";
export const FETCH_DOCUMENTS_FAIL = "FETCH_DOCUMENTS_FAIL";

export const UPLOAD_DOCUMENT_REQUEST = "UPLOAD_DOCUMENT_REQUEST";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAIL = "UPLOAD_DOCUMENT_FAIL";

export const FETCH_VISA_STATUS_REQUEST = "FETCH_VISA_STATUS_REQUEST";
export const FETCH_VISA_STATUS_SUCCESS = "FETCH_VISA_STATUS_SUCCESS";
export const FETCH_VISA_STATUS_FAIL = "FETCH_VISA_STATUS_FAIL";

// HR Types
export const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
export const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
export const FETCH_EMPLOYEES_FAIL = "FETCH_EMPLOYEES_FAIL";

export const FETCH_EMPLOYEE_DETAIL_REQUEST = "FETCH_EMPLOYEE_DETAIL_REQUEST";
export const FETCH_EMPLOYEE_DETAIL_SUCCESS = "FETCH_EMPLOYEE_DETAIL_SUCCESS";
export const FETCH_EMPLOYEE_DETAIL_FAIL = "FETCH_EMPLOYEE_DETAIL_FAIL";

export const SEARCH_EMPLOYEES_REQUEST = "SEARCH_EMPLOYEES_REQUEST";
export const SEARCH_EMPLOYEES_SUCCESS = "SEARCH_EMPLOYEES_SUCCESS";
export const SEARCH_EMPLOYEES_FAIL = "SEARCH_EMPLOYEES_FAIL";

export const GENERATE_TOKEN_REQUEST = "GENERATE_TOKEN_REQUEST";
export const GENERATE_TOKEN_SUCCESS = "GENERATE_TOKEN_SUCCESS";
export const GENERATE_TOKEN_FAIL = "GENERATE_TOKEN_FAIL";

export const FETCH_TOKENS_REQUEST = "FETCH_TOKENS_REQUEST";
export const FETCH_TOKENS_SUCCESS = "FETCH_TOKENS_SUCCESS";
export const FETCH_TOKENS_FAIL = "FETCH_TOKENS_FAIL";

export const FETCH_APPLICATIONS_REQUEST = "FETCH_APPLICATIONS_REQUEST";
export const FETCH_APPLICATIONS_SUCCESS = "FETCH_APPLICATIONS_SUCCESS";
export const FETCH_APPLICATIONS_FAIL = "FETCH_APPLICATIONS_FAIL";

export const REVIEW_APPLICATION_REQUEST = "REVIEW_APPLICATION_REQUEST";
export const REVIEW_APPLICATION_SUCCESS = "REVIEW_APPLICATION_SUCCESS";
export const REVIEW_APPLICATION_FAIL = "REVIEW_APPLICATION_FAIL";

export const REVIEW_DOCUMENT_REQUEST = "REVIEW_DOCUMENT_REQUEST";
export const REVIEW_DOCUMENT_SUCCESS = "REVIEW_DOCUMENT_SUCCESS";
export const REVIEW_DOCUMENT_FAIL = "REVIEW_DOCUMENT_FAIL";

export const FETCH_VISA_MANAGEMENT_REQUEST = "FETCH_VISA_MANAGEMENT_REQUEST";
export const FETCH_VISA_MANAGEMENT_SUCCESS = "FETCH_VISA_MANAGEMENT_SUCCESS";
export const FETCH_VISA_MANAGEMENT_FAIL = "FETCH_VISA_MANAGEMENT_FAIL";

export const SEND_NOTIFICATION_REQUEST = "SEND_NOTIFICATION_REQUEST";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_FAIL = "SEND_NOTIFICATION_FAIL";

// UI Types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
